In [3]:
import numpy
arr = numpy.array([1,2,3,4,4])
print(arr)

[1 2 3 4 4]


In [4]:
import numpy as np
arr = np.array([1,1,1])
print(arr)

[1 1 1]


In [5]:
print (np.__version__)

1.26.4


In [9]:
arr1=np.array([[2,3,4,5,5,5],[2,4,5,55,33,3]])
print(arr1)
print(arr1.ndim)

[[ 2  3  4  5  5  5]
 [ 2  4  5 55 33  3]]
2


In [11]:
arr2=np.array([1,2,3,5,6,6,7,78])
print(arr2[4])
print(arr2[1:5])

6
[2 3 5 6]


In [12]:
arr=np.array([3,3,3])
x= arr.copy()
arr[0]=55
print(arr)
print(x)
# copy don't change the orignal array 

[55  3  3]
[3 3 3]


In [13]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)
# on the other hand view  () change the orignal array show both of them 

[42  2  3  4  5]
[42  2  3  4  5]


In [18]:
arr = np.array([[1, 2, 3, 4, 5],[1,1,3,4,34]])
print(arr.shape)
#shape show the shape of the array

(2, 5)


In [20]:
arr = np.array([[1, 2, 3, 4, 5],[1,1,3,4,34]])
for x in arr:
    print(x)

[1 2 3 4 5]
[ 1  1  3  4 34]


In [21]:
# joining numpy arrays
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([1, 2, 3, 4, 5])

arr=np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 1 2 3 4 5]


In [23]:
arr1 = np.array([[1, 2, 3, 4, 5],[1,1,3,4,34]])
arr2 = np.array([[1, 2, 3, 4, 5],[1,1,3,4,34]])
arr=np.concatenate((arr1,arr2))
print(arr)
# array can be joined by stack() funtion only difference stacking is done along a new axis

[[ 1  2  3  4  5]
 [ 1  1  3  4 34]
 [ 1  2  3  4  5]
 [ 1  1  3  4 34]]


In [24]:
# splitting Numpy arrays( array_split() )
import numpy as np 
arr = np.array ([3,4,4,5,5,5,44,3,33,3,3,3])
newarr = np.array_split(arr,5)

print(arr)
print(newarr)


[ 3  4  4  5  5  5 44  3 33  3  3  3]
[array([3, 4, 4]), array([5, 5, 5]), array([44,  3]), array([33,  3]), array([3, 3])]


In [25]:
# Numpy searching arrays(where())
arr = np.array ([3,4,4,5,5,5,44,3,33,3,3,3])
newarr = np.where(arr==5)


print(newarr)


(array([3, 4, 5], dtype=int64),)


In [26]:
# sorting of arrays (sort())
arr=np.array([3,3,3,3,3,3,3,4,4,55,4])
print(np.sort(arr))


[ 3  3  3  3  3  3  3  4  4  4 55]


In [27]:
# filtering in array 
import numpy as np

arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)


[False, False, True, True]
[43 44]


In [30]:
from numpy import random 
x= random.randint(100)
y=random.rand()
print(x,y)

16 0.11533538877823557
